### ISSUE TITLE
We need an update for v1.0.3258.0

### ISSUE THREAD

**Issue by sniky21** [scripthookvdotnet/scripthookvdotnet#1460] opened 2024-07-02 23:40 UTC
We NEED an update for v1.0.3258.0

**Comment by kagikn** [comment] 2024-07-03 00:02
Duplicate of *at least* #1454 if you are getting infinite loading screen or game crash even with a nightly version of SHVDN. Duplicate of #1451 if scripts crash with the log file mentions `NativeMemory` in v1.0.3258.0 with only the stable SHVDN build v3.6.0 but not in nightly builds.

**Closed by kagikn** 2024-07-03 00:02 UTC

**Comment by devyl-90** [comment] 2024-07-11 23:47
ciao ragazzi anche io ho lo stesso problema..caricamento infinito e non va ho provato vari scripthookdonetnight ma niente qualcuno mi aiuta grazie...
