### ISSUE TITLE
[Bug]: Crash when trying to open the console

### ISSUE THREAD

**Issue by MaxCloud123** [scripthookvdotnet/scripthookvdotnet#1387] opened 2024-01-12 16:55 UTC
### What modules are you seeing the problem on?

ScriptHookVDotNet.asi (runtime)

### SHVDN Version

c3f8a6f

### Game Version

v1.0.3095.0

### Bug Description

The game crashes or freezes when trying to open the console.

[ScriptHookVDotNet.log](https://github.com/scripthookvdotnet/scripthookvdotnet/files/13921213/ScriptHookVDotNet.log)
[ScriptHookV.log](https://github.com/scripthookvdotnet/scripthookvdotnet/files/13921214/ScriptHookV.log)

### Steps To Reproduce

1. Launch the game
2. Load into story mode
3. Press F4 (crash)

### The Current Behavior

The game crashes when trying to open the console.

### The Expected Behavior

The console should open when pressing F4.

**Comment by nomakewan** [comment] 2024-01-12 18:51
Unable to reproduce using the steps you provided, running the same Nightly Release listed in your report, and the same version of GTAV. Screenshot attached.

![271590_20240112105102_1](https://github.com/scripthookvdotnet/scripthookvdotnet/assets/11485516/23edb596-d8b5-4483-9d29-81c57eba22c6)

Seems like it could be a mod conflict. What all do you have installed?

**Comment by MaxCloud123** [comment] 2024-01-12 19:18
> Seems like it could be a mod conflict. What all do you have installed?

I had no mods installed when I was making this bug report.

However I found out something else.
I decided to create a mod from the [example code from the wiki](https://github.com/scripthookvdotnet/scripthookvdotnet/wiki/Getting-Started#code-example), to test if it's just the console that's crashing for me, and that crashes too. I even modified it do something else and it crashes too. It seems that if a mod calls any SHVDN API function, the game just crashes. But this time errors are being logged into the Event Log, so I'm attaching that if it helps.
[GTAV SHVDN crash.txt](https://github.com/scripthookvdotnet/scripthookvdotnet/files/13923171/GTAV.SHVDN.crash.txt)

**Comment by nomakewan** [comment] 2024-01-12 19:44
I wonder if this is similar to the crash a friend of mine gets under rare circumstances. Are you running GTAV on a hard drive or an SSD? What are your hardware specs, if you don't mind my asking?

**Comment by MaxCloud123** [comment] 2024-01-12 19:59
GTA V is running on an HDD (But the system itself is running on an SSD)
Intel(R) Xeon(R) CPU
24GB Physical RAM
NVIDIA GeForce GTX 1660

**Comment by nomakewan** [comment] 2024-01-12 20:10
Okay, interesting. My friend's specs also has him running it on spinning rust. I run GTAV on an SSD and haven't experienced these issues. His specs:

CPU: i7-4790
RAM: 24GB DDR3
GPU: GTX 1060 6GB
OS Drive: 500GB SSD
Spinner: 7k 12TB

I've never once experienced the issues in question, but my specs aren't that far off.....except for the fact that my GTAV install is on an SSD:

CPU: i7-4790K
RAM: 32GB DDR3
GPU: GTX 1070 8GB
OS Drive: Samsung 870 EVO 1TB
Steam Drive (GTAV): Samsung 840 EVO 1TB

That makes me think more and more that this might be a race condition that rears its head when I/O buffers start to run dry.

For the discussion regarding said friend's issues, see #1365

**Comment by MaxCloud123** [comment] 2024-01-12 20:27
A race condition kinda make sense. Everything worked fine 2 days ago and with no changes this suddenly happened.
So I guess I was just lucky 2 days ago.

**Comment by kagikn** [comment] 2024-01-13 02:16
@MaxCloud123 Are you sure you are using a build at a commit in the main branch? Can't find a match by `c3f8a6f` out of the commit hash in the main branch. I logged out all the commits by `git log --pretty=oneline` and searched the outout, but still can't find one.

**Comment by nomakewan** [comment] 2024-01-13 02:18
It’s from your Nightly auto-release, not this repo.

**Comment by kagikn** [comment] 2024-01-13 02:34
Can't identify a commit in the main branch of this repo by a commit in the nightly repo, because not every commit in the nightly repo are not exclusively tied to a commit the main branch. I'll clarify what kind of commits you should report when you report bugs.

**Comment by MaxCloud123** [comment] 2024-01-13 21:48
I downloaded the latest nightly release "[ScriptHookVDotNet-v3.6.0-nightly.43](https://github.com/scripthookvdotnet/scripthookvdotnet-nightly/releases/tag/v3.6.0-nightly.43)" (Commit SHA: `31833fe`) and the crashes still occur with the same exception.

However, I accidentally found out that once the game loads into story mode, if I just wait some time (about 2-3 minutes) everything runs fine.

**Comment by nomakewan** [comment] 2024-01-13 21:50
> I downloaded the latest nightly release "[ScriptHookVDotNet-v3.6.0-nightly.43](https://github.com/scripthookvdotnet/scripthookvdotnet-nightly/releases/tag/v3.6.0-nightly.43)" (Commit SHA: `31833fe`) and the crashes still occur with the same exception.
> 
> However, I accidentally found out that once the game loads into story mode, if I just wait some time (about 2-3 minutes) everything runs fine.

And in those 2~3 minutes, is your hard drive going crazy? If it takes 2~3 minutes for the hard drive to finish streaming stuff and then once it's done streaming everything magically works fine, that would further support the theory that this is a race condition related to I/O.

**Comment by MaxCloud123** [comment] 2024-01-14 03:18
Can't tell, the hard drive activity is pretty much the same between idle system, game running on the main menu and during the 2-3 minute window.
Task manager and Process Hacker (which got renamed to Process Informer) show little to no disk activity from the process, even during loading (Less than 0.1MB/s), although Process Hacker did see high I/O activity and even some after the game loaded, however that activity lasts only a couple of seconds at most and then there are only small occasional blips of I/O.

Also from some experimenting, that 2-3 minute required wait time is only needed during the initial load from startup.
Even though when loading a save the game re-loads the story mode and all mods also seem to re-load, opening the console doesn't crash the game.

**Comment by kagikn** [comment] 2024-01-14 08:21
I realized that there are our data that need thread synchronization or need to be replaced with thread-safe collections, which includes but not limited to the `List` of pinned strings. This is accessed from the script domain thread and script threads.
https://github.com/scripthookvdotnet/scripthookvdotnet/blob/31833fea4aa7d3e48a93dfd24ac89ae8a408dd23/source/core/ScriptDomain.cs#L42
I suspect static variables in `NativeMemory` may not be visible from threads other than the ones that call the static constructors, too.

Without changing our code on this, something not good but not reproducible in a stable way may happen.

**Comment by kagikn** [comment] 2024-01-14 22:21
@MaxCloud123 Did you try [nightly.45](https://github.com/scripthookvdotnet/scripthookvdotnet-nightly/releases/tag/v3.6.0-nightly.45) for the commit 67296d3? Is SHVDN  able to open the console without having to wait for several minutes or does it crash but now with some log?

**Comment by MaxCloud123** [comment] 2024-01-15 14:29
> @MaxCloud123 Did you try [nightly.45](https://github.com/scripthookvdotnet/scripthookvdotnet-nightly/releases/tag/v3.6.0-nightly.45) for the commit [67296d3](https://github.com/scripthookvdotnet/scripthookvdotnet/commit/67296d3af6165dd52899380f112367e4d65156ea)? Is SHVDN able to open the console without having to wait for several minutes or does it crash but now with some log?

Nothing changed, when trying to open the console, the game still crashes with no error in the event log and using the mod from the example code on the wiki crashes the game with exactly the same event log error as before.

**Comment by kagikn** [comment] 2024-01-15 15:46
Can you open the console and run that example code on the wiki with SHVDN v3.6.0 without crashing? SHVDN in v3.6.0 and earlier versions calls scripting native functions in the main thread.

**Comment by MaxCloud123** [comment] 2024-01-15 16:55
Installed v3.6.0 and the game **doesn't crash** when opening the console and running the spawning Zentorno part from the Getting Started section of the example code kinda works, there are however weird oddities.

- First-time opening the console freezes the game for ~10 seconds (It does open eventually though)
  - Unlike in the nightly versions, this freeze occurs **every mod reload**, including `Reload()` and loading a save.
- Pasting multi-line text into the console looks weird
  - Pasting code from the wiki makes the code invisible, unless you delete some lines manually in the console
- When executing the code from the wiki **in the console**, there are 2 outcomes:
  - If the code  is executed for the **first time**, it crashes with `System.InvalidOperationException: Illegal call to 'Script.Wait()' outside main loop!`
    - I don't think the stack trace is needed, but if for some reason it is, then here it is: ![image](https://github.com/scripthookvdotnet/scripthookvdotnet/assets/91760380/5bdd8fa5-028a-4b11-bf1f-d9c2ed76a70d)
  - If the code is executed again, it will work just fine.
- Loading a save for the 3rd time, while having a mod that does something in `OnTick`, will crash the game during loading.
- If a mod calls any SHVDN API function in OnTick, it will crash with `System.NullReferenceException: Object reference not set to an instance of an object.`
  - ```
    System.NullReferenceException: Object reference not set to an instance of an object.
    at SHVDN.ScriptDomain.ExecuteTask(IScriptTask task)
    at SHVDN.NativeFunc.Invoke(UInt64 hash, UInt64* argPtr, Int32 argCount)
    at GTA.Native.Function.Call(Hash hash, InputArgument argument0)
    at GTA.UI.LoadingPrompt.Show(String loadingText, LoadingSpinnerType spinnerType)
    ```

**Comment by nomakewan** [comment] 2024-01-15 17:01
Passing multi-line text looking weird is a known bug that has been around forever and is planned to be fixed in #1370 so no worries on that.

**Comment by kagikn** [comment] 2024-01-16 02:05
I think I realized why SHVDN **can** crash in nightly versions when trying to do any task that requires the thread local storage (TLS) of the main thread without no event logs about .NET, including but not limited to call any native functions (the console calls script text draw functions that require the TLS of the main thread when being open). That is, our .NET thread **may** not be able to be read the updated values of the tls address and main thread id variables if the main thread (where SHV tick functions and ysc scripts run) and our .NET thread are running on different CPU cores. I believe the code needs to read and write these variables using a mutex lock to guarantee the values get updated as the intended order.

The region of lines below and the individual read funcs need to be wrapped in a mutex:
https://github.com/scripthookvdotnet/scripthookvdotnet/blob/67296d3af6165dd52899380f112367e4d65156ea/source/core/DllMain.cpp#L685-L688

## My answers of the questions in the quote (by @MaxCloud123, for behaviors in v3.6.0)
> Installed v3.6.0 and the game **doesn't crash** when opening the console and running the spawning Zentorno part from the Getting Started section of the example code kinda works, there are however weird oddities.
> 
> * First-time opening the console freezes the game for ~10 seconds (It does open eventually though)
>   
>   * Unlike in the nightly versions, this freeze occurs **every mod reload**, including `Reload()` and loading a save.
> * Pasting multi-line text into the console looks weird
>   
>   * Pasting code from the wiki makes the code invisible, unless you delete some lines manually in the console
> * When executing the code from the wiki **in the console**, there are 2 outcomes:
>   
>   * If the code  is executed for the **first time**, it crashes with `System.InvalidOperationException: Illegal call to 'Script.Wait()' outside main loop!`
>     
>     * I don't think the stack trace is needed, but if for some reason it is, then here it is: ![image](https://private-user-images.githubusercontent.com/91760380/296814396-5bdd8fa5-028a-4b11-bf1f-d9c2ed76a70d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNjY2NTQsIm5iZiI6MTcwNTM2NjM1NCwicGF0aCI6Ii85MTc2MDM4MC8yOTY4MTQzOTYtNWJkZDhmYTUtMDI4YS00YjExLWJmMWYtZDljMmVkNzZhNzBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDAwNTIzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3M2ViNGY3Y2IwNGFkZjI1ODNlM2RiMGUyODEyZWMxMGJkZjUzNmMwOGNhZmY0ZWRmNGU1M2ExYmY3ZDlmYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OVJtRHo2Gx5Dc8hAeAXrEr0Cfrom1XQaPLl-HIjkOws)
>   * If the code is executed again, it will work just fine.
> * Loading a save for the 3rd time, while having a mod that does something in `OnTick`, will crash the game during loading.
> * If a mod calls any SHVDN API function in OnTick, the mod will crash with `System.NullReferenceException: Object reference not set to an instance of an object.`
>   
>   * ```
>     System.NullReferenceException: Object reference not set to an instance of an object.
>     at SHVDN.ScriptDomain.ExecuteTask(IScriptTask task)
>     at SHVDN.NativeFunc.Invoke(UInt64 hash, UInt64* argPtr, Int32 argCount)
>     at GTA.Native.Function.Call(Hash hash, InputArgument argument0)
>     at GTA.UI.LoadingPrompt.Show(String loadingText, LoadingSpinnerType spinnerType)
>     ```

### My answers:
- > First-time opening the console freezes the game for ~10 seconds
    - Expected behavior in v3.6.0 or earlier versions. When the console opens, it pushes strings and they get pinned as UTF-8 strings in `NativeMemory.StringToCoTaskMemUTF8`. If no scripts accesses some methods that indirectly access `NativeMemory`, `NativeMemory`'s static constructor runs when the console opens. Since 5f514ef, SHVDN always ensures the static constrctor is initialized when creating a `ScriptDomain`.
- > Pasting multi-line text into the console looks weird
    - #1370 addresses the issue where console outputs can overlap with others. Expect a long time before getting merged.
- > Pasting code from the wiki makes the code invisible, unless you delete some lines manually in the console
    - I'm sorry, but I'm not fixing the input text getting invisible with like 397 characters. I'm planning to replace the console with a one made with ImGui after we separate the asi into a host API (for .NET runtime) and the script domain and SHVDN runtime stuff. `END_TEXT_COMMAND_DISPLAY_TEXT` can draw texts with up to 4 substring chunks (each chunk must be less than 99 excluding the null terminator) and 3 numbers, with more chunks, no visible texts. Would be too difficult for me to implement proper input cursor movements for long texts with script text native functions. Proper text draw of the input text with long content is not as important as that of output strings. Not too many people would manually type like 400 ASCII characters in the console IMO.
 - > If the code is executed for the first time, it crashes with System.InvalidOperationException: Illegal call to 'Script.Wait()' outside main loop!
     - Not documented but expected behavior. `World.Create*` calls `Script.Wait(int)` if the model is not loaded at the time, but the console is not allowed to call `Script.Wait(int)`.
 - > Loading a save for the 3rd time, while having a mod that does something in OnTick, will crash the game during loading.
     - Not sure what caused the game crash. Maybe I can guess the reasons if I could see what is/are registered to `OnTick`.
 - > If a mod calls any SHVDN API function in OnTick, the mod will crash with System.NullReferenceException: Object reference not set to an instance of an object.
     - Maybe because `taskQueue` runs into race conditions or `executingScript` inconsistently gets updated due to the lack of data synchronization? 
https://github.com/scripthookvdotnet/scripthookvdotnet/blob/b5a25a81835ae22724213f07ce5510a0eac50ea4/source/core/ScriptDomain.cs#L555-L557
I think we could prevent these race conditions using a lock when writing and reading them (although `taskQueue` is, however, only used in threads other than the script domain thread when creating script instances via [Script.InstantiateScripts](https://github.com/scripthookvdotnet/scripthookvdotnet/blob/67296d3af6165dd52899380f112367e4d65156ea/source/scripting_v3/GTA/Shvdn/Script/Script.cs#L291-L303) in 67296d3 (still locking that one is appropriate).

**Comment by kagikn** [comment] 2024-01-16 02:29
My PC specs FYI:

CPU: i5-4670K
RAM: 16GB DDR3
GPU: GTX 1060 6GB
OS Drive: 500GB SSD
GTA V Drive: 2TB HDD

I think CPU is the strongest concern in this issue (for info about CPU cache and the numbers of cores), but other pieces of the info may be useful for someone...

**Comment by MaxCloud123** [comment] 2024-01-16 16:43
Installed [ScriptHookVDotNet-v3.6.0-nightly.46](https://github.com/scripthookvdotnet/scripthookvdotnet-nightly/releases/tag/v3.6.0-nightly.46) (Commit 200388b5143a4bc2e57f66d20d49c0e36a1c0b0d) and the game **doesn't crash** when the console is opened immediately after loading in and any mods that do anything in `OnTick` also **don't crash** the game.

I don't know whenever this issue is fixed permanently or if my system is currently playing nicely, though. I guess time will tell.

**Comment by MaxCloud123** [comment] 2024-01-26 21:28
The crashes from `System.AccessViolationException` have returned. Version [ScriptHookVDotNet-v3.6.0-nightly.56](https://github.com/scripthookvdotnet/scripthookvdotnet-nightly/releases/tag/v3.6.0-nightly.56) c52b5b75018f975feec962ff6e2e157306bea312

[GTAV SHVDN crash    again.txt](https://github.com/scripthookvdotnet/scripthookvdotnet/files/14069429/GTAV.SHVDN.crash.again.txt)
[ScriptHookVDotNet.log](https://github.com/scripthookvdotnet/scripthookvdotnet/files/14069442/ScriptHookVDotNet.log)

It crashes with the same conditions as before (opening the console, mod calling an API that ultimately calls a Native, etc.), though it's less consistent than before, it sometimes feels like crashing and sometimes it doesn't.
I also found out, that running Steam in offline mode will always cause this behavior.

**Comment by kagikn** [comment] 2024-01-28 07:16
Shit, it may be better to not try to completely solve this issue for now. I think synchronizing data of the SHVDN runtime that can be used with multiple threads doesn't guarantee complete thread safety when mess with the game's memory via natives or direct memory access on a thread other than the main thread where the game's logic is run. Problem is, we **HAVE** to hook a function in the game before we can tick SHVDN on the main thread in a way RPH won't run into a hard crash when it or its plugins throws exceptions...

**Comment by kagikn** [comment] 2024-08-19 14:42
I believe this issue is already resolved as how #1454 got resolved.

**Closed by kagikn** 2024-08-19 14:42 UTC
Labels: bug
