### ISSUE TITLE
[Bug]: Missing scripts folder freeze

### ISSUE THREAD

**Issue by Michael21107** [scripthookvdotnet/scripthookvdotnet#1473] opened 2024-07-13 20:50 UTC
### What modules are you seeing the problem on?

ScriptHookVDotNet.asi (runtime), ScriptHookVDotNet3.dll (v3 SDK/API), ScriptHookVDotNet2.dll (v2 SDK/API)

### SHVDN Version

fd3eca5cc035686f8d513c69765769223764bfd9

### Game Version

v1.0.3258.0

### Bug Description

after launching the game with `_scripts` folder and trying to open the console, the game stops responding but it sounds like the engine and some ambiance can still be heard
![Grand Theft Auto V 13-Jul-24 22_44_15](https://github.com/user-attachments/assets/077abc5f-f994-4f50-88d1-4e28f73074ce)
the game window turns white after clicking in it when it's not responding (frozen)
[ScriptHookVDotNet.log](https://github.com/user-attachments/files/16203642/ScriptHookVDotNet.log)
### Steps To Reproduce

1. rename the `scripts` folder to `_scripts` while ''scripts'' is still specified as the folder to use in the SHVDN INI
2. launch the game
3. click the SHVDN console key (mine is set to F2, which I clicked) 

### The Current Behavior

the game freezes without the console opening

### The Expected Behavior

SHVDN console would open

**Comment by Michael21107** [comment] 2024-07-13 21:05
update: having an empty scripts folder (alongside the _scripts at least) is gonna yield the same results, just with SHVDN not logging the `[WARNING]`
[ScriptHookVDotNet.log](https://github.com/user-attachments/files/16203655/ScriptHookVDotNet.log)

**Comment by kagikn** [comment] 2024-07-13 23:57
Duplicate of #1473, that's what I thought from what this issue is.

**Closed by kagikn** 2024-07-13 23:57 UTC
Labels: bug

**Comment by Michael21107** [comment] 2024-07-14 00:47
are you also aware that the game always crashes when more than 1 script is installed, 1 or 0 just makes the game freeze when the SHVDN console is open?

**Comment by kagikn** [comment] 2024-07-14 01:02
> are you also aware that the game always crashes when more than 1 script is installed, 1 or 0 just makes the game freeze when the SHVDN console is open?

Since #1454 discusses a nondeterministric issue, I think what you stated can happen.

**Comment by Michael21107** [comment] 2024-07-14 01:14
gotcha, thanks
