### ISSUE TITLE
[Bug]: Latest game version doesn't work well with this dotnet 

### ISSUE THREAD

**Issue by MOnkeMan5009** [scripthookvdotnet/scripthookvdotnet#1514] opened 2024-10-28 12:32 UTC
### 📦 What modules are you seeing the problem on?

ScriptHookVDotNet.asi (runtime), ScriptHookVDotNet3.dll (v3 SDK/API), ScriptHookVDotNet2.dll (v2 SDK/API)

### 🛠️ SHVDN Version

latest nightly 135

### 🎮 Game Version

v1.0.3351.0

### 🐛 Bug Description

While using the old gen wasted logic script, it completely breaks with newest game update. very rarely it works. most of the time it breaks. I noticed after this update to newest version had to completely redo my mods folder and every single file.

### 🔄 Steps To Reproduce

Install old gen wasted logic from gta5mods
latest shv dot net
test it out. it aint working as supposed to

### ⚠️ Current Behavior

the script tries to do its thing but the slow motion without "wasted" appears. the script is broken. with this update

### 🎯 Expected Behavior

to do what the mod was intended to do. no wasted screen once dead or slow motion

**Comment by kagikn** [comment] 2024-10-28 12:53
I'm assuming you're talking about [the old gen wasted logic script by F121](https://www.gta5-mods.com/scripts/old-gen-wasted-screen-logic), but can you tell me which one? The issue will be closed as not planned if there's no proof that the issue is responsible to SHVDN  anyway, however.

**Comment by kagikn** [comment] 2024-10-28 14:56
Closing as not relevant to SHVDN's codebase. I tested [the old gen wasted logic script by F121](https://www.gta5-mods.com/scripts/old-gen-wasted-screen-logic) in v1.0.3095.0, which was the latest game version as of the first script release, and v1.0.3351.0, and then I concluded that the author just coded too poorly. It spammed the wasted audio clip even in v1.0.3095.0.

ILSpy told me the script doesn't call any SHVDN methods that internally do direct memory reading or writing, too. It means script is likely to behave in the same way between different game versions than if it relied on ones that internally do direct memory reading or writing.

**Closed by kagikn** 2024-10-28 14:56 UTC
Labels: bug

**Comment by MOnkeMan5009** [comment] 2024-10-28 22:36
> I'm assuming you're talking about [the old gen wasted logic script by F121](https://www.gta5-mods.com/scripts/old-gen-wasted-screen-logic), but can you tell me which one? The issue will be closed as not planned if there's no proof that the issue is responsible to SHVDN anyway, however.

yeah thats it. the latest version.
The thing is he himself told me to update scripthookvdotnet a while ago, and it worked for a few weeks/ a month or so again just fine. Now after the latest version, some updates or whatever, it completely broke again.
