### ISSUE TITLE
[Bug]: Logging of non-scripts folders dlls

### ISSUE THREAD

**Issue by Michael21107** [scripthookvdotnet/scripthookvdotnet#1343] opened 2023-11-13 18:27 UTC
### What modules are you seeing the problem on?

ScriptHookVDotNet.asi (runtime), ScriptHookVDotNet3.dll (v3 SDK/API), ScriptHookVDotNet2.dll (v2 SDK/API)

### SHVDN Version

a69b254

### Game Version

v1.0.3028.0

### Bug Description

SHVDN log shows stuff like xscanner and khorio common which are not in scripts folder

### Steps To Reproduce

download [the latest SHVDN CI action build](https://github.com/scripthookvdotnet/scripthookvdotnet/suites/18140490338/artifacts/1046025834)
install [xscanner](https://www.lcpdfr.com/downloads/gta5mods/scripts/20002-xscanner/) 
look at the SHVDN.log

### The Current Behavior

it logs these dlls

### The Expected Behavior

it wont log these dlls
[ScriptHookVDotNet.log](https://github.com/scripthookvdotnet/scripthookvdotnet/files/13339535/ScriptHookVDotNet.log)won't

**Comment by kagikn** [comment] 2023-11-13 22:36
Can't reproduce the issue, and SHVDN doesn't log dlls XScanner uses such as `Khorio.Common.dll` in my game. I don't see any of them have the constant string `ScriptHookVDotNet` either, though. are there missing steps?

**Comment by Michael21107** [comment] 2023-11-14 00:31
khorio common is in GTAV and xscanner is in gtav/plugins/lspdfr i never thought shvdn would recognize these files, that's why i opened this issue

**Comment by kagikn** [comment] 2023-11-14 00:52
I said like SHVDN (at a69b254) doesn't log the dlls that comes with XScanner in my game . Without providing additional info to reproduce, I'll close this issue as not planned.

**Comment by Michael21107** [comment] 2023-11-14 01:39
[ScriptHookVDotNet.log](https://github.com/scripthookvdotnet/scripthookvdotnet/files/13343612/ScriptHookVDotNet.log)
[RagePluginHook.log](https://github.com/scripthookvdotnet/scripthookvdotnet/files/13343618/RagePluginHook.log)
here i loaded RPH and lspdfr after a while, if it helps and u tell me how to do so, I can enable the Assembly binding logging

**Comment by kagikn** [comment] 2023-11-14 02:00
My apologies for just testing by only loading SHVDN but not loading RPH. Considering the timestamp in the both logs, this is strange because the SHVDN log was written earlier. Anyway, I must test with LSPDFR loaded and see what happens in my game, hoping XScanner doesn't mess with the SHVDN log, which makes this issue not responsible to SHVDN.

**Comment by Michael21107** [comment] 2023-11-14 03:13
yea, the first time i wasn't starting RPH

**Comment by kagikn** [comment] 2023-11-14 10:49
Nah, I don't see any logs about DLLs XScanner uses even after I went into duty in LSPDFR. Needs more info before someone else can easily reproduce for sure.

**Comment by Michael21107** [comment] 2023-11-14 11:02
wont enabling the assembly binding logging help?

**Comment by kagikn** [comment] 2023-11-14 13:20
Assembly bind failure logging shouldn't do nothing if no code fails to load assemblies, if I understand what the feature means. Make sure you have no irrelevant DLLs such as ones for LSPDFR in your scripts folder...

**Comment by Michael21107** [comment] 2023-11-14 14:28
I'm so sorry, didnt think i could fuck up so much...i had a copy of pack_default with xscanner in my scripts folder lmao
![image](https://github.com/scripthookvdotnet/scripthookvdotnet/assets/121039033/789c5f8d-b7ae-4f14-9f42-42e7c6e6394d)

**Closed** 2023-11-14 14:33 UTC
Labels: bug
