### ISSUE TITLE
[Bug]: crash when I hit f4

### ISSUE THREAD

**Issue by artur733** [scripthookvdotnet/scripthookvdotnet#1452] opened 2024-06-28 16:42 UTC
### What modules are you seeing the problem on?

ScriptHookVDotNet.asi (runtime)

### SHVDN Version

I can't because console is not opening.

### Game Version

v1.0.3258.0

### Bug Description

Game is not loading scripts and When I am trying to open console game freezes for few seconds and next crashes.

### Steps To Reproduce

For example:

1. Open game in story mode
2. Click F4 (or any other button that's opening the console)
3. Game freezes and crashes

### The Current Behavior

unplayable. scripts not loading and console crashes the game , sometimes it's crashes only when I start game.

### The Expected Behavior

When I hit f4 console is opening without game crashing and scripts are loading

**Comment by kagikn** [comment] 2024-06-28 16:50
Sorry, but actually this bug report is duplicate of #1451, which is already resolved. The same cause.

**Closed by kagikn** 2024-06-28 16:50 UTC
Labels: bug
