### ISSUE TITLE
[Bug]: my Game got infinite loading after download scripthookvdotnet by nighty and putting scripts in my scripts folder ?

### ISSUE THREAD

**Issue by itsmygta** [scripthookvdotnet/scripthookvdotnet#1476] opened 2024-07-15 18:01 UTC
### What modules are you seeing the problem on?

ScriptHookVDotNet2.dll (v2 SDK/API)

### SHVDN Version

0d5d4356

### Game Version

v1.0.3258

### Bug Description

as soon as i download Nightys scripthookvdotnet and putiing it in my main GTA folder and install like 2-3 scripts and putting them into my scripts folder my Game wont load it got stuck on loading the Game after the 2nd GTA Online ad 

### Steps To Reproduce

i get no error code ?

### The Current Behavior

It does nothing in the txt file thats created is only written that they resolved the dll to api and nothong happens i get stuck on my loading screen ?
[ScriptHookVDotNet.log](https://github.com/user-attachments/files/16238398/ScriptHookVDotNet.log)

### The Expected Behavior

it should start my fricking GAME

**Comment by kagikn** [comment] 2024-07-15 23:05
Duplicate of #1454

**Closed by kagikn** 2024-07-15 23:05 UTC
Labels: bug
