### ISSUE TITLE
[Bug]: Euphoria Helpers appear to do nothing.

### ISSUE THREAD

**Issue by Ethirix** [scripthookvdotnet/scripthookvdotnet#1259] opened 2023-07-04 03:06 UTC
### What modules are you seeing the problem on?

ScriptHookVDotNet3.dll (v3 SDK/API)

### SHVDN Version

3.6.0

### Game Version

1.0.2944.0

### Bug Description

Calling `Start()` on seemingly all `CustomHelper` derived Euphoria helper classes does nothing, however calling `StaggerFall` through the Native `CREATE_NM_MESSAGE` and `GIVE_PED_NM_MESSAGE` functions correctly, however with no way to configure the Message.

```csharp
        private void OnKeyDown(object sender, KeyEventArgs key)
        {
            if (key.KeyCode == Keys.Subtract)
            {
                Function.Call(Hash.SET_PED_TO_RAGDOLL, Game.Player.Character, 4000, 5000, 1, 1, 1, 0);
                SendEuphoriaMessage(NaturalMotionMessages.StopAllBehaviors);
                SendEuphoriaMessage(NaturalMotionMessages.StaggerFall); //functions as expected
            }
            else if (key.KeyCode == Keys.Multiply)
            {
                Game.Player.Character.Euphoria.StaggerFall.Start(); //does nothing
            }
        }
```
Below is the equivalent of calling `SendEuphoriaMessage(NaturalMotionMessages.StaggerFall);` with the `messageId` as an `int`.
```csharp
Function.Call(Hash.CREATE_NM_MESSAGE, true, 1151);
Function.Call(Hash.GIVE_PED_NM_MESSAGE, Game.Player.Character);
```

### Steps To Reproduce

Call `Start()` on almost any of Euphoria `CustomHelper` Classes such as `StaggerFall`.

### The Current Behavior

The Character ragdolls and nothing else.

### The Expected Behavior

The Euphoria/NaturalMotion Message should be sent to the Character and the action then take place, such as falling over while staggering, instead of flopping to the floor.

**Comment by kagikn** [comment] 2023-07-04 04:05
I'm sorry, but kind of duplicate of #1145. Already fixed in 59afba0 and 984e944. Euphoria helpers in v3.6.0 does not work in the game version v1.0.2802.0 and later ones, though, that is correct.

I tried testing this in the build 78de768, and both blocks do almost the same thing.
```cs
        private void OnKeyDown(object sender, KeyEventArgs key)
        {
            if (key.KeyCode == Keys.Subtract)
            {
                Function.Call(Hash.SET_PED_TO_RAGDOLL, Game.Player.Character, 4000, 5000, 1, 1, 1, 0);
		Function.Call(Hash.CREATE_NM_MESSAGE, true, 0 /* id for stopAllBehaviours  */);
		Function.Call(Hash.GIVE_PED_NM_MESSAGE, Game.Player.Character);
		Function.Call(Hash.CREATE_NM_MESSAGE, true, 1151 /* id for staggerFall */);
		Function.Call(Hash.GIVE_PED_NM_MESSAGE, Game.Player.Character);
            }
            else if (key.KeyCode == Keys.Multiply)
            {
                Game.Player.Character.Euphoria.StaggerFall.Start(); // should do the same thing as the block above except for ragdoll time
            }
        }
```

I should have clarify this, but it would have been great if you had tested the latest nightly version to see if your issue persisted. My work for the issue template rewarded in how I can response issues that quickly with firm proves, though.

**Closed by kagikn** 2023-07-04 04:05 UTC
Labels: bug

**Comment by Ethirix** [comment] 2023-07-04 11:50
I'm somewhat new to this, I'm sorry.
I built from source and it works, however would I have to wait for a new release to be able to upload the files to [GTA5 Mods](gta5-mods.com/) or could I bundle the built files. 
I don't exactly want everyone that downloads it to have to complile it themselves every time.

**Comment by kagikn** [comment] 2023-07-04 11:57
I know what you are concerning. And that is why I'm focusing on only adding methods for  frequently used native functions in ysc scripts that are not well documented in the Native DB and finding design flaws of the new features not shipped in any stable versions.
v3.7.0 should be published within 1 week if I managed to do stuff properly. Your patience would be appreciated, and it might be rewarded.

**Comment by Ethirix** [comment] 2023-07-04 14:35
The only reason I bought it up was because it seems "intuitive" to use `Start(int)` and I was using another resource, which has since been defunct by the `CustomHelper`s being broken, and they used `Start(int)`. It doesn't matter too much since the messages only need to last for the duration of the Ragdoll itself and since they don't function when the character is not in Ragdoll, it works out.

**Comment by kagikn** [comment] 2023-07-17 22:59
Duplicate of #1145

Sorry to bump, but this is just a mark.
